transform_tolerance: 0.4
obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.34,0.25],[-0.34,0.25],[-0.34,-0.25],[0.34,-0.25]]
inflation_radius: 0.45

observation_sources: scan scan_filtered lms200 lms200_scan_filtered kinect

scan: {data_type: LaserScan, topic: scan, expected_update_rate: 0.3, marking: false, clearing: true}

scan_filtered: {data_type: LaserScan, topic: scan_filtered, expected_update_rate: 0.3, marking: true, clearing: false}

lms200: {data_type: LaserScan, topic: lms200, expected_update_rate: 0.3, marking: false, clearing: true}

lms200_scan_filtered: {data_type: LaserScan, topic: lms200_scan_filtered, expected_update_rate: 0.3, marking: true, clearing: false}

kinect: {data_type: PointCloud2, topic: kinect/depth_registered/points_filtered_cut_floor, expected_update_rate: 0.7, marking: true, clearing: true}
